### Protótipo da etl, verificando manualmente cada coluna para aplicar posteriormente no código python

In [200]:
import pandas as pd

df_empresa = pd.read_csv(r'../../data/csv/raw/dados/EmpresaInativas.csv', index_col=0, sep=',', low_memory=False)

dataframe_empresa = df_empresa.copy()

pd.set_option('display.max_columns', None)   
pd.set_option('display.max_rows', None)      
pd.set_option('display.width', 300)         
pd.set_option('display.max_colwidth', None) 
pd.set_option('display.float_format', '{:.2f}'.format)  

display(dataframe_empresa.head())

,ï»¿cnpj,razao_social,nome_fantasia,cod_logradouro,nome_logradouro,numero_residencia,numero_lote,cod_bairro,nome_bairro,situacao_empresa,data_abertura_empresa,data_encerramento,cod_grupo,nome_grupo,cnae,desc_atividade,atividade_principal,atividade_vig_sanitaria,atividade_predominante,incomodo,latitude,longitude
0,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4313400,OBRAS DE TERRAPLENAGEM,S,N,S,N,NaN,NaN
1,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4330404,SERVIÃOS DE PINTURA DE EDIFÃCIOS EM GERAL,N,N,N,N,NaN,NaN
2,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,15,GUARDA E LOCACAO DE BENS MOVEIS,7732201,"ALUGUEL DE MÃQUINAS E EQUIPAMENTOS PARA CONSTRUÃÃO SEM OPERADOR, EXC ANDAIMES",N,N,N,N,NaN,NaN
3,00388321000105,CAMADA OLISI CONSTRUCOES LTDA,NaN,61620,Rua TristÃ£o da Cunha,NaN,6,884,Cohab Ibura de Cima,BAIXADO,1995-01-01,2000-12-01,6,"JURIDICO, ECONOMICO E TECNICO ADMINISTRATIVO",7415200,SEDES DE EMPRESAS E UNIDADES ADMINISTRATIVAS LOCAI,S,N,S,N,NaN,NaN
4,00388321000105,CAMADA OLISI CONSTRUCOES LTDA,NaN,61620,Rua TristÃ£o da Cunha,NaN,6,884,Cohab Ibura de Cima,BAIXADO,1995-01-01,2000-12-01,1,CONSTRUCAO CIVIL,4120400,CONSTRUÃÃO DE EDIFÃCIOS,N,N,S,N,NaN,NaN

### Antes de fazer a análise, eu preciso mesclar as colunas com o dataframe

In [201]:
dataframe_empresa.rename({'ï»¿cnpj': 'cnpj'}, axis=1, inplace=True)
dataframe_empresa.columns

Index(['cnpj', 'razao_social', 'nome_fantasia', 'cod_logradouro', 'nome_logradouro', 'numero_residencia', 'numero_lote', 'cod_bairro', 'nome_bairro', 'situacao_empresa', 'data_abertura_empresa', 'data_encerramento', 'cod_grupo', 'nome_grupo', 'cnae', 'desc_atividade', 'atividade_principal',
       'atividade_vig_sanitaria', 'atividade_predominante', 'incomodo', 'latitude', 'longitude'],
      dtype='object')

# Verificando coluna por coluna
A ideia é validar cada coluna se tem valores faltantes, duplicados (se a regra de negócio pedir) ou se a coluna está com o tipo errado.

- [x] **cnpj (text)**
- [x] **razao_social (text)**
- [x] **nome_fantasia (text)**
- [x] **cod_logradouro (text)**
- [x] **nome_logradouro (text)**
- [x] **numero_residencia (text)**
- [ ] **numero_lote (text)**
- [ ] **cod_bairro (numeric)**
- [ ] **nome_bairro (text)**
- [ ] **situacao_empresa (text)**
- [ ] **data_abertura_empresa (timestamp)**
- [ ] **data_encerramento (text)**
- [ ] **cod_grupo (numeric)**
- [ ] **nome_grupo (text)**
- [ ] **cnae (numeric)**
- [ ] **desc_atividade (text)**
- [ ] **atividade_principal (text)**
- [ ] **atividade_vig_sanitaria (text)**
- [ ] **atividade_predominante (text)**
- [ ] **incomodo (text)**
- [ ] **latitude (numeric)**
- [ ] **longitude (numeric)**

### Informações do conjunto de dados

In [202]:
dataframe_empresa.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 382792 entries, 0 to 382791
Data columns (total 22 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   cnpj                     382792 non-null  object
 1   razao_social             382792 non-null  object
 2   nome_fantasia            264139 non-null  object
 3   cod_logradouro           382789 non-null  object
 4   nome_logradouro          382779 non-null  object
 5   numero_residencia        168294 non-null  object
 6   numero_lote              382789 non-null  object
 7   cod_bairro               382789 non-null  object
 8   nome_bairro              382789 non-null  object
 9   situacao_empresa         382789 non-null  object
 10  data_abertura_empresa    382786 non-null  object
 11  data_encerramento        85153 non-null   object
 12  cod_grupo                382789 non-null  object
 13  nome_grupo               382789 non-null  object
 14  cnae                     382789 non-null  object
 15  desc_atividade           382789 non-null  object
 16  atividade_principal      382789 non-null  object
 17  atividade_vig_sanitaria  382789 non-null  object
 18  atividade_predominante   382789 non-null  object
 19  incomodo                 382789 non-null  object
 20  latitude                 327059 non-null  float64
 21  longitude                327056 non-null  float64
dtypes: float64(2), object(20)
memory usage: 67.2+ MB

### Verificando tipo de cada coluna

In [203]:
dataframe_empresa.dtypes

cnpj                        object
razao_social                object
nome_fantasia               object
cod_logradouro              object
nome_logradouro             object
numero_residencia           object
numero_lote                 object
cod_bairro                  object
nome_bairro                 object
situacao_empresa            object
data_abertura_empresa       object
data_encerramento           object
cod_grupo                   object
nome_grupo                  object
cnae                        object
desc_atividade              object
atividade_principal         object
atividade_vig_sanitaria     object
atividade_predominante      object
incomodo                    object
latitude                   float64
longitude                  float64
dtype: object

### Verificando coluna por coluna

In [204]:
# Segunda coluna -> cnpj

dataframe_empresa['cnpj'].isna().value_counts()
# False -> 381634
dataframe_empresa['cnpj'].isnull().value_counts()
# False -> 381634
dataframe_empresa['cnpj'].duplicated().value_counts()

# True     233742
# False    147892

dataframe_empresa[dataframe_empresa['cnpj'].duplicated()].head()
# dataframe_empresa['cnpj'].dtype

,cnpj,razao_social,nome_fantasia,cod_logradouro,nome_logradouro,numero_residencia,numero_lote,cod_bairro,nome_bairro,situacao_empresa,data_abertura_empresa,data_encerramento,cod_grupo,nome_grupo,cnae,desc_atividade,atividade_principal,atividade_vig_sanitaria,atividade_predominante,incomodo,latitude,longitude
1,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4330404,SERVIÃOS DE PINTURA DE EDIFÃCIOS EM GERAL,N,N,N,N,NaN,NaN
2,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,15,GUARDA E LOCACAO DE BENS MOVEIS,7732201,"ALUGUEL DE MÃQUINAS E EQUIPAMENTOS PARA CONSTRUÃÃO SEM OPERADOR, EXC ANDAIMES",N,N,N,N,NaN,NaN
4,00388321000105,CAMADA OLISI CONSTRUCOES LTDA,NaN,61620,Rua TristÃ£o da Cunha,NaN,6,884,Cohab Ibura de Cima,BAIXADO,1995-01-01,2000-12-01,1,CONSTRUCAO CIVIL,4120400,CONSTRUÃÃO DE EDIFÃCIOS,N,N,S,N,NaN,NaN
7,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,26,OUTRAS ATIVIDADES VAREJISTAS,4744099,COMÃRCIO VAREJISTA DE MATERIAIS DE CONSTRUÃÃO EM GERAL,S,N,N,S,NaN,NaN
8,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,26,OUTRAS ATIVIDADES VAREJISTAS,4759899,COMÃRCIO VAREJISTA DE OUTROS ARTIGOS DE USO DOMÃSTICO NÃO ESPECIF ANTERIORMENTE,N,N,N,N,NaN,NaN

### Pegarei alguns cnpj especificos para entender

In [205]:
dataframe_empresa.query("cnpj == '03561119000121'")

,cnpj,razao_social,nome_fantasia,cod_logradouro,nome_logradouro,numero_residencia,numero_lote,cod_bairro,nome_bairro,situacao_empresa,data_abertura_empresa,data_encerramento,cod_grupo,nome_grupo,cnae,desc_atividade,atividade_principal,atividade_vig_sanitaria,atividade_predominante,incomodo,latitude,longitude
0,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4313400,OBRAS DE TERRAPLENAGEM,S,N,S,N,NaN,NaN
1,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4330404,SERVIÃOS DE PINTURA DE EDIFÃCIOS EM GERAL,N,N,N,N,NaN,NaN
2,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,15,GUARDA E LOCACAO DE BENS MOVEIS,7732201,"ALUGUEL DE MÃQUINAS E EQUIPAMENTOS PARA CONSTRUÃÃO SEM OPERADOR, EXC ANDAIMES",N,N,N,N,NaN,NaN

In [206]:
dataframe_empresa.query("cnpj == '12271079000174'")

,cnpj,razao_social,nome_fantasia,cod_logradouro,nome_logradouro,numero_residencia,numero_lote,cod_bairro,nome_bairro,situacao_empresa,data_abertura_empresa,data_encerramento,cod_grupo,nome_grupo,cnae,desc_atividade,atividade_principal,atividade_vig_sanitaria,atividade_predominante,incomodo,latitude,longitude
6,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,1,CONSTRUCAO CIVIL,4399102,MONTAGEM E DESMONTAGEM DE ANDAIMES E OUTRAS ESTRUTURAS TEMPORÃRIAS,N,N,S,N,NaN,NaN
7,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,26,OUTRAS ATIVIDADES VAREJISTAS,4744099,COMÃRCIO VAREJISTA DE MATERIAIS DE CONSTRUÃÃO EM GERAL,S,N,N,S,NaN,NaN
8,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,26,OUTRAS ATIVIDADES VAREJISTAS,4759899,COMÃRCIO VAREJISTA DE OUTROS ARTIGOS DE USO DOMÃSTICO NÃO ESPECIF ANTERIORMENTE,N,N,N,N,NaN,NaN
9,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,26,OUTRAS ATIVIDADES VAREJISTAS,4761003,COMÃRCIO VAREJISTA DE ARTIGOS DE PAPELARIA,N,N,N,N,NaN,NaN
10,12271079000174,RODRIGO SILVESTRE DE SANTANA ME,CONSTRUTIVA,56707,Rua Raposo Tavares,NaN,50,884,Cohab Ibura de Cima,SUSPENSO,2010-07-20,NaN,22,OUTROS SERVICOS,5620102,SERVIÃOS DE ALIMENTAÃÃO PARA EVENTOS E RECEPÃÃES - BUFÃ,N,S,N,S,NaN,NaN

### Exceto MEI (Microempreendedor Individual) que pode ter um CNAE (código nacional de atividade empresarial) principal e 15 secundários, os demais tipos de empresa podem ter um CNAE principal e 99 secundários.

Fonte: https://www.contabilizei.com.br/contabilizei-responde/quantos-cnaes-pode-ter-uma-empresa/?utm_source=chatgpt.com

### Verificando valores unicos para ver se tem um comportamento inesperado

In [207]:
cnpj_com_letras = dataframe_empresa.loc[
    dataframe_empresa['cnpj'].str.contains(r'[^0-9]', na=False),
    'cnpj'
]
print(cnpj_com_letras)

509                       d5c287535e322c31d4613fe022d53698
510                       a196173d129b26931603ecd7ff6be21f
511                       cad02cf066b5609d0246e2b93c1bf25c
512                       cad02cf066b5609d0246e2b93c1bf25c
513                       0b7a9157a873590ecd124eb8021f7dca
514                       dd13a5ce1b884a958e79cf1867e8cc19
515                       7e3b5ca1ef1f65189daa7b7dbb545c1c
516                       7e3b5ca1ef1f65189daa7b7dbb545c1c
517                       06d477ee25a4d989be91dcec7d89e48e
518                       ec49767654c9ecd11603ecd7ff6be21f
519                       ddb0c16788375c099daa7b7dbb545c1c
1888                      dd13a5ce1b884a958e79cf1867e8cc19
1889                      4ef3a98a866ee05ecd124eb8021f7dca
1890                      043d8c60156878e9be91dcec7d89e48e
1891                      ec5cb5f3fe45b48dbe91dcec7d89e48e
1892                      72f5f933fd72cff71603ecd7ff6be21f
1893                      3c233c4d1208d40c8e79cf1867e8cc19
1894                      e5071b88aa8bb6d7176df4728619142c
1895                      117407c6f2d70de08e79cf1867e8cc19
1896                      fc6bde6ac1fbab5575234379af146d63
1897                      adc21d574aafc27e9daa7b7dbb545c1c
1898                      64b933b923e01db7be91dcec7d89e48e
1899                      75e83c22f29709128e79cf1867e8cc19
1900                      a00ec7355171de1391e796325bc06316
1901                      e7eb9f4f528d79619daa7b7dbb545c1c
1902                      a14e1619a950625db7e87098721d8c1d
1903                      8b104aea752602da2a13d3ea4dcea995
1904                      264545ae4958d36d0246e2b93c1bf25c
1905                      1ad77d2b2af7865acd124eb8021f7dca
1906                      25c158818220033bd4613fe022d53698
1907                      1ad77d2b2af7865acd124eb8021f7dca
1908                      b2bc4d60f76254cc0246e2b93c1bf25c
1909                      43b846969785579c1603ecd7ff6be21f
1910                      cc5df116e72e1d788e79cf1867e8cc19
1911                      c945794d2886732175234379af146d63
1912                      926287eb694e13c6acc7ff10b872fdd2
1913                      063ad82d8c6837fe1603ecd7ff6be21f
1914                      11e1efa347ef6eacacc7ff10b872fdd2
1915                      d5a78bb08f42db96d4613fe022d53698
1916                      7a99f150db5c4055d4613fe022d53698
1917                      d58a833f684da9f675234379af146d63
3805                      02b541641f714407d4613fe022d53698
3806                      871fa8c9b76ccd2275234379af146d63
9114                      e32585eb4739ee71344d77602867ec09
9115                      f30e12e8d26e39359daa7b7dbb545c1c
9116                      1c5fcd7d17731886cd124eb8021f7dca
9117                      3edd7910fdf255c28e79cf1867e8cc19
9118                      679d463adf3476fb8e79cf1867e8cc19
9119                      0c673a8e5d58f00b0246e2b93c1bf25c
9120                      96e42429504d219ad4613fe022d53698
9121                      c8ef5cd6ecb042d6acc7ff10b872fdd2
9122                      3fb9c849afa906f300b3f2da8c6092e4
9123                      7df6e13c6f40521f75234379af146d63
9124                      e9f77047cb4cc568cd124eb8021f7dca
9125                      6c756e63a4fa8c20d8b209292c0ce31d
9126                      e32149f384038cff75234379af146d63
9127                      c8e57671233697a9be91dcec7d89e48e
9128                      4869ed9fac594053acc7ff10b872fdd2
9129                      0fe145f4a96b13d39059f4de09ff292e
9130                      e893df34389029dbd8b209292c0ce31d
9131                      475eb7b0e6bf695c75234379af146d63
9132                      be1aa342951ae5081603ecd7ff6be21f
9133                      304d5504eb4b58390246e2b93c1bf25c
9134                      a0ff449d791929198e79cf1867e8cc19
9135                      3c40b37ef3239b4a0246e2b93c1bf25c
9136                      282c5dcee20562f7be91dcec7d89e48e
9137                      6f8af9ebfe28594f8e79cf1867e8cc19
9138                      23e432b64a5a5666fd56e249ecb9d5ae
9139                      59da6b7ec7e0cf53acc7ff10b872fdd2
9140                      4f63519974a7faa0acc7ff10b872fdd2
9141                      5626dee207bbc7e30246e2b93c1bf25c
9142                      f286c30895d85562be91dcec7d89e48e
9143                      66826f9ce55e850eadaf8563a746964a
9144                      22cfd774dbb403b1be91dcec7d89e48e
9145                      045fcbdb380cca4ad65600efcabb160f
9146                      20c01f950443fd460f6d944cc78fcd6f
9147                      9855b296a545fd1b75234379af146d63
9148                      8895be7aba60203a8e79cf1867e8cc19
9149                      93d9ae4efe778abbcd124eb8021f7dca
9150                      ec2a0f00ee36c3ee0246e2b93c1bf25c
9151                      ec2a0f00ee36c3ee0246e2b93c1bf25c
9152                      6c293cc3a7a84844ccef8250158c4d35
9153                      6c293cc3a7a84844ccef8250158c4d35
9154                      0fe145f4a96b13d39059f4de09ff292e
9155                      52540b63a6fabdd38e79cf1867e8cc19
9156                      bc78477196e0c006cd124eb8021f7dca
9157                      bff9b909a9c6cc860246e2b93c1bf25c
9158                      2b6f0283dc6811da1603ecd7ff6be21f
9159                      ee71d352542c6b77ec557718ffae83ea
9160                      f24147857274e11275234379af146d63
9161                      038484a8f58bf280adaf8563a746964a
9162                      1737b24be445ea81d8b209292c0ce31d
9163                      0e7a8f17d0aaa4f8be91dcec7d89e48e
9164                      3fa0af63b592b449a19f0d576c6c1e10
9165                      0047d80cea5881c8cd124eb8021f7dca
9166                      bfa68be3f3564427d4613fe022d53698
9167                      fed3163c500bf3498e79cf1867e8cc19
9168                                      6a01614cfb4b2d61
9169                      6388d07305c5edcd00b3f2da8c6092e4
9170                      29925d2f2538d47dbe91dcec7d89e48e
9171                      5b58de4c6f5f03e3eba8895eefa603bb
9172                      13741a7232da8d6675234379af146d63
9173                      3ed319f4ad8e0260045275b95ed789d6
9174                      3ed319f4ad8e0260045275b95ed789d6
9175                      a9fca38769bd15aeeba8895eefa603bb
9176                      a9fca38769bd15aeeba8895eefa603bb
9177                      e6d0802cdfd16177d4613fe022d53698
9178                      31bfb6e676e546a00246e2b93c1bf25c
9179                      76af0fa7ad08a05f9daa7b7dbb545c1c
9180                      548920afa4b0abe4ae08d57f53945088
9181                      9693e029d69a470c344d77602867ec09
9182                      93daf1211588e561d4613fe022d53698
9183                      ea731ea7e2ec92c48e79cf1867e8cc19
9184                      90956c1b38ed12a20246e2b93c1bf25c
9185                      16fcd993f3b677cf91e796325bc06316
9186                      3695565df92745009daa7b7dbb545c1c
9187                      02f8fc0b0a2304481603ecd7ff6be21f
9188                      0b875d2a6936d33c9daa7b7dbb545c1c
9189                      bc32fc1c3cec65f5ccef8250158c4d35
9190                      cddad746fb9082d81603ecd7ff6be21f
9191                      8de432db2f3c6c129daa7b7dbb545c1c
9192                      cc106ac65776e2a9be91dcec7d89e48e
9193                      4b068a51f499cc770246e2b93c1bf25c
9194                      e4792c07c1065bad0246e2b93c1bf25c
9195                      eca5b1aacea0d4d29daa7b7dbb545c1c
9196                      91798e92748833c41603ecd7ff6be21f
9197                      bff044b296c30e929daa7b7dbb545c1c
9198                      2a07e0897f57c016d4613fe022d53698
9199                      35454f50e64b472ad4613fe022d53698
9200                      88fe8e667fd6c132be91dcec7d89e48e
9201                      95a54887e8e9bc019daa7b7dbb545c1c
9202                      3ca5e42f150ff393d8b209292c0ce31d
9203                      47faf1ebff70947ed8b209292c0ce31d
9204                      be161e76e3927d5cbe91dcec7d89e48e
9205                      df83fe144e684ddbd8b209292c0ce31d
9206                      c97044c7f4750668ec24828071529570
9207                      86c4036ffb5e27c675234379af146d63
9208                      99d7e251a85b2349cd124eb8021f7dca
9209                      ce84159011b11fb1acc7ff10b872fdd2
9210                      66130403cfa09b32acc7ff10b872fdd2
9211                      8ddcc0125ffce90b344d77602867ec09
9212                      21a44089ea96818b0246e2b93c1bf25c
9213                      d461aade58eedadacd124eb8021f7dca
9214                      d461aade58eedadacd124eb8021f7dca
9215                      6b6a0319b94f396a75234379af146d63
9216                      ba09880c72580ae04fe449743fbbb46a
9217                      da3c9a3f83d85e9075234379af146d63
9218                      727f3c9eed369787be91dcec7d89e48e
9219                      471bb335bd869b52d5dc6acd7fe6bee3
9220                      9a7fc3922b252e4ccd124eb8021f7dca
9221                      891778586bc1024b0246e2b93c1bf25c
9222                      770e4290d75618e61603ecd7ff6be21f
9223                                      81e871d965f45bad
9224                      d039f59b6413743abe91dcec7d89e48e
9225                      65e0a08a632a1baaadaf8563a746964a
9226                      bd3c36c4af749e7a8e79cf1867e8cc19
9227                      1de7e82389ed4462cd124eb8021f7dca
9228                      c4c18ba423620f8c9daa7b7dbb545c1c
9229                      4a8152ce56288678acc7ff10b872fdd2
9230                      663780c0b46c2e6d75234379af146d63
9231                      67ba783186a7bd21d8b209292c0ce31d
9232                      1152c83b48c0ad07cd124eb8021f7dca
9233                      fd04d8614713709f0246e2b93c1bf25c
9234                      5fcd1c88c041c9d5d8b209292c0ce31d
9235                                      e8eb9912244d85da
9236                      081716e35e445b17ccef8250158c4d35
9237                                      e8eb9912244d85da
9238                      081716e35e445b17ccef8250158c4d35
9239                      2a971317f3d50ede0246e2b93c1bf25c
9240                      c19e7ab46bc1b5b31603ecd7ff6be21f
9241                      6cd82c07657f5d86be91dcec7d89e48e
9242                      9454a90e1074e1d575234379af146d63
9243                      e84a1e02d675bc484eca53bce1fbea00
9244                      4a9abfc7619d71ae8e79cf1867e8cc19
9245                      f718bd6faf677a6f344d77602867ec09
9246                      37be69114ca17118d4613fe022d53698
9247                      039a58f5ff3d70851603ecd7ff6be21f
9248                      9b536ca4998e107b1603ecd7ff6be21f
9249                      7a10160304291159be91dcec7d89e48e
9250                                      ef7c28980bb415a2
9251                      3f3f2f62141c4220acc7ff10b872fdd2
9252                      bcb846a0d423f001344d77602867ec09
9253                      80f2cc764e33244691e796325bc06316
9254                      c7007f5c6c5912df1ed8b02446055311
9255                      6dfb8956633cf19bbe91dcec7d89e48e
9256                      75485f1a0f1dba0ceaa3dba62f869c7f
9257                      3a2fe675ecfa3dbe9daa7b7dbb545c1c
9258                      834af63ba65deb9b0246e2b93c1bf25c
9259                      7c7cf754951118d2d8b209292c0ce31d
9260                      7516a1a4329baa8a75234379af146d63
9261                      38bc334241da86df75234379af146d63
9262                      c7cd9d417186395375234379af146d63
9263                      02fa462c690cda77344d77602867ec09
9264                      65482c4b7622f4d1344d77602867ec09
9265                      e760d4d48b9ffc6dcd124eb8021f7dca
9266                      d1bcd59edcdf288b9daa7b7dbb545c1c
9267                      7886f4241102d23c016a94d4634387ac
9268                      3c0914845f22a8a81603ecd7ff6be21f
9269                      f080647e8ffaa43dccef8250158c4d35
9270                      4ebbe404e21abae80246e2b93c1bf25c
9271                      5a46429076d50a65acc7ff10b872fdd2
9272                      9c91052e9c5dd92cd8b209292c0ce31d
9273                      a2fc093ace87c3939daa7b7dbb545c1c
9274                      b4dfe17d6d437826d8b209292c0ce31d
9275                      5bce04eba010e206acc7ff10b872fdd2
9276                      eea47fe1d2b1cb119daa7b7dbb545c1c
9277                                      27bdd4a9245c8ebc
9278                      de768a380bb9a2ce75234379af146d63
9279                      4bba0430b7263c26cd124eb8021f7dca
9280                      a765593fd0b031add8b209292c0ce31d
9281                      fd50ee42d627893aec24828071529570
9282                      3b7788b6140d48b5344d77602867ec09
9283                      8aca705689b8e11dadaf8563a746964a
9284                      59b0941c3df4d80c344d77602867ec09
9285                      434c21a74a7b9b1d1603ecd7ff6be21f
9286                      7912030a78be8048acc7ff10b872fdd2
9287                      7f8e32b831e8d2b98e79cf1867e8cc19
9288                      38b54f5291ab7419cd124eb8021f7dca
9289                      4da9f4d2676e563bacc7ff10b872fdd2
9290                      a976e10e8348e98675234379af146d63
9291                      b7b698532ce62c7775234379af146d63
9292                      77e65fea61f88c49be91dcec7d89e48e
9293                      61a647312e79e76c344d77602867ec09
9294                      64cf90e29f261a95be91dcec7d89e48e
9295                      8544ead7b896be030246e2b93c1bf25c
9296                      592792cef40c9985be91dcec7d89e48e
9297                      592792cef40c9985be91dcec7d89e48e
9298                      4c5148c6bafab4298e79cf1867e8cc19
9299                      d7d7f01a5459793d0246e2b93c1bf25c
9300                      cb8722e235824ec28e79cf1867e8cc19
9301                      a311455066a4e3dcd8b209292c0ce31d
9302                      fdd32209285cd8b4cd124eb8021f7dca
9303                      ced213def58c682b1603ecd7ff6be21f
9304                      51e77e4fd9c57c698e79cf1867e8cc19
9305                      439514f17fc53a36d9b9d69331e93258
9306                      769621005bd6c6030246e2b93c1bf25c
9307                      c604592df4ad35c82a13d3ea4dcea995
9308                      79e398941484237475234379af146d63
9309                      e8a678605625d87ed8b209292c0ce31d
9310                      11687619c7c1ee1aacc7ff10b872fdd2
9311                      273206e140f0035d8e79cf1867e8cc19
9312                      742125cdc4b83bad8e79cf1867e8cc19
9313                      9c259c0cb8fa92798e79cf1867e8cc19
9314                      dfb60a62f7ec4a9d1603ecd7ff6be21f
9315                      5a10e0c736cde5a0344d77602867ec09
9316                      2337e3f8143a4265acc7ff10b872fdd2
9317                      2337e3f8143a4265acc7ff10b872fdd2
9318                      0d1a917465643a4a75234379af146d63
9319                      319f6da1da39164f75234379af146d63
9320                      0a56b51b6ebac8c30246e2b93c1bf25c
9321                                      861a477e3db51886
9322                      2d995fd89e3f41c2d8b209292c0ce31d
9323                      cb20eb7bfd4c27fffafaebd1073fc2f4
9324                      3172df0c99a0c8738e79cf1867e8cc19
9325                      56e3ff00bc5a7a168e79cf1867e8cc19
9326                      2ca8955080602751d8b209292c0ce31d
9327                      4e51e083ebb369190246e2b93c1bf25c
9328                      34b5366512d62e8075234379af146d63
9329                      7bfdd76ee68496a61603ecd7ff6be21f
9330                                      726c3f62fdffb7b6
9331                      a563f351bcfa302cd8b209292c0ce31d
9332                      a795630d01e44cbc9daa7b7dbb545c1c
9333                      9c1fbc1fa1e767ccbe91dcec7d89e48e
9334                      6530f92518ec0aeaacc7ff10b872fdd2
9335                                      861a477e3db51886
9336                      2d995fd89e3f41c2d8b209292c0ce31d
9337                      74fccb492195f25ed4613fe022d53698
9338                      8eb3e4a7d0a71bcf968646cfc1e328f2
9339                      6a1e9dfc7cbf906acd124eb8021f7dca
9340                      53e34d3abd61c0acacc7ff10b872fdd2
9341                      a96368831d9aa87ed4613fe022d53698
9342                                      1498b0b98a21c36f
9343                      80e5d40871320f2f344d77602867ec09
9344                      6a39bf52e1962de4be91dcec7d89e48e
9345                      4aec8fbdf9841ca8be91dcec7d89e48e
9346                      9726f127f5f212ab8e79cf1867e8cc19
9347                      f01cf5618137fdd7344d77602867ec09
9348                      459182cabe3eaab6d8b209292c0ce31d
9349                      459182cabe3eaab6d8b209292c0ce31d
9350                      30cb28d869aa499a8e79cf1867e8cc19
9351                      a9f0d5b2a37ef4c58e79cf1867e8cc19
16463                     adc29ad077a48b690246e2b93c1bf25c
16464                                     c1b920ab4bde2250
16465                                     c9a15d2d46bc0937
16466                     3059f3956f26d3ca18d3fc4836304ca5
16467                     1e5777abc55a1260d4613fe022d53698
16468                     6af93823cbb6b8b3d8b209292c0ce31d
16469                     84d5cf31d3077f6ecd124eb8021f7dca
16470                     b55869a5a893d75dcd124eb8021f7dca
16784                     42ededa48d0e3013d8b209292c0ce31d
16785                     61f75477b26a92b7acc7ff10b872fdd2
20094                     fe4b5e10e5ee1fd98e79cf1867e8cc19
20396                     b08bf338cfb172d38e79cf1867e8cc19
30577                     880a7c29adf558bdd8b209292c0ce31d
30578                     5ef93036e26f3ce575234379af146d63
30579                     5ef93036e26f3ce575234379af146d63
34434                     1a26183e07ddfdac9daa7b7dbb545c1c
34435                     28f0deca98e74b1cbe91dcec7d89e48e
34436                     b5e873623ec6145bacc7ff10b872fdd2
40100                     1341824bdc9aa9109daa7b7dbb545c1c
40101                                     1049d266e0e3a8b9
40102                     2c8ed3107835dee875234379af146d63
40103                     fdf0ae8b3ec99509d8b209292c0ce31d
40104                     fdf0ae8b3ec99509d8b209292c0ce31d
40105                     50333f871c53304a9daa7b7dbb545c1c
40106                     bec13802f56f1624cd124eb8021f7dca
40107                     4da9f4d2676e563bacc7ff10b872fdd2
40108                     2506a5dfd73449ead68a63999a0ebf35
40109                                     1647568cbb819175
40110                     80570e41db63f5699daa7b7dbb545c1c
40111                     1e6232f57c85d1cf8e79cf1867e8cc19
47805                     eb414793c5c7b81b0246e2b93c1bf25c
47806                     27cecef158f084ea75234379af146d63
51552                     b2d05b983851a89b8e79cf1867e8cc19
51553                                     21aa46cc22abd484
51554                                     21aa46cc22abd484
51555                     98ebf1cdfd92b2fcfafaebd1073fc2f4
51556                     98ebf1cdfd92b2fcfafaebd1073fc2f4
52326                     c793526326eb1d6d968646cfc1e328f2
52327                     5be51b9f8a8b7261d8b209292c0ce31d
54639                     b8a7d0fbcc10fbfbcd124eb8021f7dca
55027                     f49bbf0d470623bf75234379af146d63
55028                     b407bb42c6d66fd49daa7b7dbb545c1c
55029                     d92c495e8c09fa628e79cf1867e8cc19
55030                     2712e48b62780e819daa7b7dbb545c1c
55031                     549b7167e54c6fe29daa7b7dbb545c1c
55032                     a1806c7e4453ae3e8e79cf1867e8cc19
55033                     a1e7ef9e85fdbfcd9daa7b7dbb545c1c
55034                     de54d51edad3c42a75234379af146d63
55035                     05301895628873021603ecd7ff6be21f
55036                     d913397d995303a5d4613fe022d53698
55037                     11efab78a6314c6c0246e2b93c1bf25c
55038                     1480a8cc4fad6a5a9daa7b7dbb545c1c
55039                     c3943b263da2632ed8b209292c0ce31d
55040                     7217c10a05102a3f1603ecd7ff6be21f
55041                     358d482fa3c619f39daa7b7dbb545c1c
55042                     ef39f79ba792a031d4613fe022d53698
55043                     1602d2993923703900b3f2da8c6092e4

### Infelizmente esse conjunto de dados contém cnpj com registros em hash, irei considerar isso como um ruído e separar em outro dataset

In [208]:
dataframe_empresa[dataframe_empresa['cnpj'].isin(cnpj_com_letras)].to_csv(
    '../../data/csv/raw/EmpresasInativasComHash.csv', index=False
)
dataframe_empresa = dataframe_empresa[~dataframe_empresa['cnpj'].isin(cnpj_com_letras)]

dataframe_empresa.head()

,cnpj,razao_social,nome_fantasia,cod_logradouro,nome_logradouro,numero_residencia,numero_lote,cod_bairro,nome_bairro,situacao_empresa,data_abertura_empresa,data_encerramento,cod_grupo,nome_grupo,cnae,desc_atividade,atividade_principal,atividade_vig_sanitaria,atividade_predominante,incomodo,latitude,longitude
0,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4313400,OBRAS DE TERRAPLENAGEM,S,N,S,N,NaN,NaN
1,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,1,CONSTRUCAO CIVIL,4330404,SERVIÃOS DE PINTURA DE EDIFÃCIOS EM GERAL,N,N,N,N,NaN,NaN
2,03561119000121,ROTENO CONSTRUCOES LTDA,NaN,9342,Rua Azevedo Cruz,NaN,213,884,Cohab Ibura de Cima,INAPTO,1999-12-01,NaN,15,GUARDA E LOCACAO DE BENS MOVEIS,7732201,"ALUGUEL DE MÃQUINAS E EQUIPAMENTOS PARA CONSTRUÃÃO SEM OPERADOR, EXC ANDAIMES",N,N,N,N,NaN,NaN
3,00388321000105,CAMADA OLISI CONSTRUCOES LTDA,NaN,61620,Rua TristÃ£o da Cunha,NaN,6,884,Cohab Ibura de Cima,BAIXADO,1995-01-01,2000-12-01,6,"JURIDICO, ECONOMICO E TECNICO ADMINISTRATIVO",7415200,SEDES DE EMPRESAS E UNIDADES ADMINISTRATIVAS LOCAI,S,N,S,N,NaN,NaN
4,00388321000105,CAMADA OLISI CONSTRUCOES LTDA,NaN,61620,Rua TristÃ£o da Cunha,NaN,6,884,Cohab Ibura de Cima,BAIXADO,1995-01-01,2000-12-01,1,CONSTRUCAO CIVIL,4120400,CONSTRUÃÃO DE EDIFÃCIOS,N,N,S,N,NaN,NaN

In [209]:
# Segunda coluna -> razao_social

dataframe_empresa['razao_social'].isna().value_counts()

# False    381634

# Retornou algumas empresas com Nan
# Irei substituir Nan por "não informado"
texto_nao_informado = 'Não informado'

dataframe_empresa['razao_social'] = dataframe_empresa['razao_social'].replace('.', texto_nao_informado)
dataframe_empresa['razao_social'] = dataframe_empresa['razao_social'].fillna(texto_nao_informado)
dataframe_empresa[dataframe_empresa['razao_social'].isna()] # Não existe mais NaN
dataframe_empresa['razao_social'] = dataframe_empresa['razao_social'].str.title() # Formatação para apenas a primeira letra da palavra ficar maiuscula
dataframe_empresa['razao_social'].unique()
dataframe_empresa['razao_social'].isnull().value_counts()

# False  382792

dataframe_empresa['razao_social'].duplicated().value_counts()

# True     305851
# False     76941

dataframe_empresa[['razao_social', 'cnpj', 'cnae']].duplicated().value_counts() # verificando se existe cnpj com cnae e nome duplicado

# False    370575
# True      12217

dataframe_empresa[dataframe_empresa[['razao_social', 'cnpj', 'cnae']].duplicated() == True].head()

dataframe_empresa['razao_social'].dtype

dtype('O')

In [210]:
# Terceira coluna -> nome_fantasia

dataframe_empresa['nome_fantasia'].isna().value_counts()

# False    264139
# True     118653

dataframe_empresa['nome_fantasia'] = dataframe_empresa['nome_fantasia'].replace('.', texto_nao_informado)
dataframe_empresa['nome_fantasia'] = dataframe_empresa['nome_fantasia'].fillna(texto_nao_informado)
dataframe_empresa[dataframe_empresa['nome_fantasia'].isna()] # Não existe mais NaN
dataframe_empresa['nome_fantasia'] = dataframe_empresa['nome_fantasia'].str.title() # Formatação para apenas a primeira letra da palavra ficar maiuscula
dataframe_empresa['nome_fantasia'].unique()
dataframe_empresa['nome_fantasia'].isnull().value_counts()

# False  382792

dataframe_empresa['nome_fantasia'].duplicated().value_counts()

# True     305851
# False     76941

dataframe_empresa[['nome_fantasia', 'cnpj', 'cnae']].duplicated().value_counts() # verificando se existe cnpj com cnae e nome duplicado

# False    370575
# True      12217

False    369442
True      12192
Name: count, dtype: int64

In [211]:
# Quarta coluna -> cod_logradouro

dataframe_empresa['cod_logradouro'].isna().value_counts()

# False    382789
# True          3

dataframe_empresa['cod_logradouro'] = dataframe_empresa['cod_logradouro'].fillna(texto_nao_informado)
dataframe_empresa['cod_logradouro'].unique()
dataframe_empresa['cod_logradouro'].isnull().value_counts()

# False    381634


dataframe_empresa['cod_logradouro'].duplicated().value_counts()
# True     376932
# False      4702
dataframe_empresa[['cod_logradouro', 'cnpj', 'cnae']].duplicated().value_counts()

# False    369768
# True      11866

False    369768
True      11866
Name: count, dtype: int64

In [212]:
# Quinta coluna -> nome_logradouro

dataframe_empresa['nome_logradouro'].isna().value_counts()

# nome_logradouro
# False    381624
# True         10
# Name: count, dtype: int64

dataframe_empresa['nome_logradouro'] = dataframe_empresa['nome_logradouro'].fillna(texto_nao_informado)
dataframe_empresa['nome_logradouro'].unique()
dataframe_empresa['nome_logradouro'].isnull().value_counts()

# False    381634


dataframe_empresa['nome_logradouro'].duplicated().value_counts()

# nome_logradouro
# True     376955
# False      4679
# Name: count, dtype: int64

dataframe_empresa[['nome_logradouro', 'cnpj', 'cnae']].duplicated().value_counts()

# False    369768
# True      11866
# Name: count, dtype: int64

False    369768
True      11866
Name: count, dtype: int64

In [213]:
# Sexta coluna -> numero_residencia

dataframe_empresa['numero_residencia'].isna().value_counts()

# numero_residencia
# True     214105
# False    167529
# Name: count, dtype: int64

dataframe_empresa[dataframe_empresa['numero_residencia'].isna()].head()
dataframe_empresa['numero_residencia'] = dataframe_empresa['numero_residencia'].fillna(texto_nao_informado)
dataframe_empresa['numero_residencia'].unique()
dataframe_empresa['numero_residencia'].isnull().value_counts()

# numero_residencia
# False    381634
# Name: count, dtype: int64

dataframe_empresa['numero_residencia'].duplicated().value_counts()

# numero_residencia
# True     379507
# False      2127
# Name: count, dtype: int64

dataframe_empresa[dataframe_empresa['numero_residencia'].duplicated()].head()

dataframe_empresa[['numero_residencia', 'cnpj', 'cnae']].duplicated().value_counts()

# False    376022
# True       5612
# Name: count, dtype: int64

False    376022
True       5612
Name: count, dtype: int64

In [214]:
# Sétima coluna -> numero_lote

dataframe_empresa['numero_lote'].isna().value_counts()

# False    381631
# True          3

dataframe_empresa[dataframe_empresa['numero_lote'].isna()].head()
dataframe_empresa['numero_lote'] = dataframe_empresa['numero_lote'].fillna(texto_nao_informado)
dataframe_empresa['numero_lote'].unique()
dataframe_empresa['numero_lote'].isnull().value_counts()

# numero_lote
# False    381634
# Name: count, dtype: int64

dataframe_empresa['numero_lote'].duplicated().value_counts()

# numero_lote
# True     378192
# False      3442
# Name: count, dtype: int64

dataframe_empresa[dataframe_empresa['numero_lote'].duplicated()].head()

dataframe_empresa[['numero_lote', 'cnpj', 'cnae']].duplicated().value_counts()

# False    370313
# True      11321
# Name: count, dtype: int64

False    370313
True      11321
Name: count, dtype: int64

In [215]:
# Oitava coluna -> cod_bairro

dataframe_empresa['cod_bairro'].isna().value_counts()

# cod_bairro
# False    381631
# True          3
# Name: count, dtype: int64

dataframe_empresa[dataframe_empresa['cod_bairro'].isna()]

dataframe_empresa['cod_bairro'].unique()

# array(['884', '400', '396', '612', '574', '370', '388', '361', '930',
#        '353', '620', '566', '582', '558', '540', '337', '345', '507',
#        '493', '949', '426', '523', '310', '329', '299', '280', '302',
#        '434', '531', '515', '485', '191', '183', '175', '698', '477',
#        '442', '469', '450', '132', '167', '159', '124', '272', '108',
#        '19', '736', '680', '655', '671', '647', '140', '94', '86', '728',
#        '710', '701', '817', '663', '116', '27', '35', '809', '760', '78',
#        '60', '787', '779', '795', '43', '833', '825', '51', '850', '264',
#        '248', '256', nan, '205', '230', '213', '221', '604', '744', '590',
#        '752', '914', '868', '922', '906', '892', '876', '841', '418'],
#       dtype=object)

dataframe_empresa['cod_bairro'] = dataframe_empresa['cod_bairro'].fillna(texto_nao_informado)
dataframe_empresa['cod_bairro'].duplicated().value_counts()

# cod_bairro
# True     381540
# False        94
# Name: count, dtype: int64


dataframe_empresa[['cod_bairro', 'cnpj', 'cnae']].duplicated().value_counts()

# False    369565
# True      12069
# Name: count, dtype: int64

False    369565
True      12069
Name: count, dtype: int64

In [222]:
# Nona coluna -> nome_bairro

dataframe_empresa['nome_bairro'].isna().value_counts()

# # nome_bairro
# # False    381631
# # True          3
# # Name: count, dtype: int64

dataframe_empresa[dataframe_empresa['nome_bairro'].isna()]

dataframe_empresa['nome_bairro'].unique()

# array(['Cohab   Ibura de Cima', 'Passarinho', 'Dois Unidos',
#        'Brejo da Guabiraba', 'Brejo de Beberibe', 'Beberibe',
#        'Linha do Tiro', 'Porto da Madeira', 'Ponto de Parada', 'Cajueiro',
#        'Corrego do Jenipapo', 'Nova Descoberta', 'Macaxeira',
#        'Vasco da Gama', 'Alto Jose Bonifacio', 'Agua Fria', 'Fundao',
#        'Apipucos', 'Alto do Mandu   Sitio Grande', 'Alto Santa Terezinha',
#        'Bomba do Hemeterio', 'Alto Jose do Pinho', 'Campina do Barreto',
#        'Arruda', 'Peixinhos', 'Campo Grande', 'Hipodromo', 'Casa Amarela',
#        'Morro da Conceicao', 'Mangabeira', 'Monteiro', 'Tamarineira',
#        'Rosarinho', 'Encruzilhada', 'Iputinga', 'Poco', 'Casa Forte',
#        'Parnamirim', 'Santana', 'Aflitos', 'Gracas', 'Jaqueira',
#        'Espinheiro', 'Torreao', 'Santo Amaro', 'Recife', 'Varzea',
#        'Cordeiro', 'Torre', 'Zumbi', 'Madalena', 'Derby', 'Paissandu',
#        'Boa Vista', 'Cidade Universitaria', 'Engenho do Meio', 'Torroes',
#        'San Martin', 'Prado', 'Soledade', 'Santo Antonio', 'Sao Jose',
#        'Bongi', 'Ilha do Retiro', 'Ilha do Leite', 'Coelhos',
#        'Mustardinha', 'Afogados', 'Mangueira', 'Ilha Joana Bezerra',
#        'Estancia', 'Jiquia', 'Cabanga', 'Areias', 'Imbiribeira', 'Pina',
#        'Brasilia Teimosa', nan, 'Boa Viagem', 'Ibura', 'Ipsep', 'Jordao',
#        'Sitio dos Pintos   Sao Bras', 'Caxanga', 'Dois Irmaos', 'Curado',
#        'Toto', 'Jardim Sao Paulo', 'Coqueiral', 'Sancho', 'Tejipio',
#        'Barro', 'Cacote', 'Guabiraba'], dtype=object)

dataframe_empresa['nome_bairro'] = dataframe_empresa['nome_bairro'].fillna(texto_nao_informado)
dataframe_empresa['nome_bairro'] = dataframe_empresa['nome_bairro'].str.title()
dataframe_empresa['nome_bairro'].duplicated().value_counts()

# nome_bairro
# True     381540
# False        94
# Name: count, dtype: int64


dataframe_empresa[['nome_bairro', 'cnpj', 'cnae']].duplicated().value_counts()

# False    369565
# True      12069
# Name: count, dtype: int64

False    369565
True      12069
Name: count, dtype: int64

In [ ]:
# Décima coluna -> situacao_empresa

dataframe_empresa['situacao_empresa'].isna().value_counts()

# situacao_empresa
# False    381631
# True          3
# Name: count, dtype: int64

dataframe_empresa[dataframe_empresa['situacao_empresa'].isna()]

dataframe_empresa['situacao_empresa'].unique()

# array(['INAPTO', 'BAIXADO', 'SUSPENSO', nan], dtype=object)

dataframe_empresa['situacao_empresa'] = dataframe_empresa['situacao_empresa'].fillna(texto_nao_informado)
dataframe_empresa['situacao_empresa'] = dataframe_empresa['situacao_empresa'].str.title()
dataframe_empresa['situacao_empresa'].duplicated().value_counts()

# situacao_empresa
# True     381630
# False         4
# Name: count, dtype: int64

dataframe_empresa[['situacao_empresa', 'cnpj', 'cnae']].duplicated().value_counts()

# False    369768
# True      11866
# Name: count, dtype: int64

False    369768
True      11866
Name: count, dtype: int64